on: [issues]

jobs:
    reproduire-sur-stackblitz:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            id: checkout
            uses: actions/checkout@v4
          - name: Test Local Action
            id: test-action
            uses: ./
            with:
              repo-token: ${{ secrets.GITHUB_TOKEN }}
          
