on: [issues]

jobs:
    reproduire-sur-stackblitz:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: huang-julien/reproduire-sur-stackblitz
          with:
            repo-token: ${{ secrets.GITHUB_TOKEN }}
