on: [issues]

jobs:
    reproduire-sur-stackblitz:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Test Local Action
          id: test-action
          uses: ./
          with:
            repo-token: ${{ secrets.GITHUB_TOKEN }}
          
